embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"exit\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/main/assets/main.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"exit\"\n"
  "mask: \"player\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -161.0\n"
  "      y: 153.0\n"
  "    }\n"
  "    rotation {\n"
  "      x: -0.09383262\n"
  "      w: 0.995588\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"exit\"\n"
  "  }\n"
  "  data: 64.16396\n"
  "  data: 65.13427\n"
  "  data: 31.743958\n"
  "}\n"
  ""
}
