go.property("speed", 150)

function init(self)

	self.input = {
		left = false,
		right = false,
		up = false,
		down = false
	}

	self.vel = vmath.vector3(0, 0, 0)

	self.missoes = {
		{ texto = "Get all documents (100 points)", concluida = false, pontos = 100 },
		{ texto = "Get to exit (200 pontos)", concluida = false, pontos = 200 }
	}
	self.pontos = 0
	self.documentos_coletados = 0
	self.total_documentos = 3

	-- Mostrar missões e pontos no início
	msg.post("/interface#interface", "atualizar_pontos", { valor = self.pontos })
	msg.post("/interface#interface", "atualizar_missoes", { lista = self.missoes })

	
	msg.post(".", "acquire_input_focus")

	sound.play("background")
	sound.play("catch_item")
end

function update(self, dt)
	local dir = vmath.vector3()

	if self.input.left then dir.x = dir.x - 1 end
	if self.input.right then dir.x = dir.x + 1 end
	if self.input.up then dir.y = dir.y + 1 end
	if self.input.down then dir.y = dir.y - 1 end

	if dir.x ~= 0 or dir.y ~=0 then
		dir = vmath.normalize(dir)
		go.set_position(go.get_position() + dir * self.speed * dt)
	end
end

function on_input(self, action_id, action)
	if action_id == hash("left") then
		if action.pressed then
			self.input.left = true
		elseif action.released then
			self.input.left = false
		end
	end
	if action_id == hash("right") then
		if action.pressed then
			self.input.right = true
		elseif action.released then
			self.input.right = false
		end
	end
	if action_id == hash("up") then
		if action.pressed then
			self.input.up = true
		elseif action.released then
			self.input.up = false
		end
	end
	if action_id == hash("down") then
		if action.pressed then
			self.input.down = true
		elseif action.released then
			self.input.down = false
		end
	end
	local isMoving = self.input.up or self.input.down or self.input.left or self.input.right
	if isMoving and not isSoundPlaying then
		sound.play("#footsteps")
		isSoundPlaying = true
	elseif isSoundPlaying and not isMoving then
		sound.stop("#footsteps")
		isSoundPlaying = false
	end
end

function concluir_missao(self, indice)
	if not self.missoes[indice].concluida then
		self.missoes[indice].concluida = true
		self.pontos = self.pontos + self.missoes[indice].pontos
		msg.post("/interface#interface", "atualizar_pontos", { valor = self.pontos })
		msg.post("/interface#interface", "atualizar_missoes", { lista = self.missoes })
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("contact_point_response") then
		if message.normal.y > 0.1 then
			self.input.down = false 
		end
		if message.normal.y < 0.1 then
			self.input.up = false
		end
		if message.normal.x > 0.1 then
			self.input.left = false 
		end
		if message.normal.x < 0.1 then
			self.input.right = false
		end
		local pos = go.get_position()
		go.set_position(vmath.vector3(pos.x, pos.y, 0))
	end
	if message_id == hash("trigger_response") and message.enter then
		-- Colisão com documento
		if message.other_group == hash("documento") then
			go.delete(message.other_id)
			self.documentos_coletados = self.documentos_coletados + 1

			if self.documentos_coletados == self.total_documentos then
				concluir_missao(self, 1) -- missão 2 concluida
			end
		end
		-- colisão com guarda
		if message.other_group == hash("enemy") then
			sound.play("#fx")
			print("Jogador detectado!")
			msg.post("main:/interface", "flash_alerta")
		end
	end
end