go.property("speed", 70) -- pode ser diferente
go.property("top_limit", 550) -- depende da posição (e da direçãobdo movimento: aqui são valores de Y)
go.property("bottom_limit", 200) -- depende da posição (e da direçãobdo movimento: aqui são valores de Y)

function init(self)
	self.dir = 1
	go.set(".", "scale.y", go.get(".", "scale.x") * -1) -- flip vertical(opcional - depende do sprite usado)
end

function update(self, dt)
	local pos = go.get_position()
	pos.y = pos.y + self.speed * self.dir * dt

	if pos.y >= self.top_limit then
		pos.y = self.top_limit
		self.dir = -1
		go.set(".", "scale.y", go.get(".", "scale.y") * -1)
	elseif pos.y <= self.bottom_limit then
		pos.y = self.bottom_limit
		self.dir = 1
		go.set(".", "scale.y", go.get(".", "scale.y") * -1)
	end

	go.set_position(pos)
end